version: '3.8'
services:
  mysqldb:
    container_name: mysqldb-con-qu
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3308:3306"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 60s
      start_period: 20s
      retries: 3
      timeout: 10s
  poc-bank-application-quarkus:
    container_name: poc-con-qu
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.legacy-jar
    #./docker/Dockerfile.jvm
    ports:
      - "9090:9090"
      - "5005:5005"
    restart: on-failure
    depends_on:
      mysqldb:
        condition: service_healthy

