version: '3.8'
services:
  rabbitmq:
    container_name: rabbitmq-container
    build:
      context: .
      dockerfile: ./Dockerfile.rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - total_bridge
  #    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
#      interval: 60s
#      start_period: 20s
#      retries: 3
#      timeout: 10s
  mysqldb:
    container_name: mysqldb-con-qu
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3308:3306"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 60s
      start_period: 20s
      retries: 3
      timeout: 10s
    networks:
      - total_bridge
  poc-bank-application-quarkus:
    container_name: poc-con-qu
    build:
      context: .
      dockerfile: ./Dockerfile.jvm
    #./docker/Dockerfile.jvm
    ports:
      - "9090:9090"
      - "5005:5005"
    restart: on-failure
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - total_bridge
    #      rabbitmq:
    #        condition: service_healthy
networks:
  total_bridge:
    driver: bridge