# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: ./mvnw package -Dquarkus.package.type=uber-jar
    - name: Docker Login
    # You may pin to the exact commit or the version.
    # uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
      uses: docker/login-action@v3.0.0
      with:
      # Server address of Docker registry. If not set then will default to Docker Hub
        registry: https://hub.docker.com
      # Username used to log against the Docker registry
        username: manudeep
      # Password or personal access token used to log against the Docker registry
        password: dckr_pat_dCIjS2VciFXo0A2W6rUJvIVL1R4
      # Specifies whether the given registry is ECR (auto, true or false)
        ecr: manudeep/quarkus-with-mysql
      # Log out from the Docker registry at the end of a job
      #logout: # optional, default is true


    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
#    - name: Update dependency graph
#      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
